apiVersion: v2
name: monitoring
description: A Helm chart for monitoring system
type: application

version: 0.1.0

dependencies:
  - name: victoria-metrics-k8s-stack
    version: "0.68.0"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-metrics-k8s-stack.enabled
  - name: victoria-logs-single
    version: "0.11.24"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-logs-single.enabled
  - name: victoria-logs-collector
    version: "0.2.7"
    repository: https://victoriametrics.github.io/helm-charts
    condition: victoria-logs-collector.enabled    